import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export async function getServerSideProps() {
  const res = await fetch(`https://restcountries.com/v3.1/all`)
  const data = await res.json()
  return { props: { data } }
}

export default function Home({ data }) {
  console.log(data);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>

          {
            data.map((item, index) => {
              return (
                <div key={index} className={styles.card}>
                  <div className={styles.image}>
                    <Image src={item.flags.svg} width="300px" height="200px" layout="responsive" objectFit="cover" alt="country flag" />
                  </div>
                  <div className={styles.cardInfo}>
                    <div className={styles.info}>
                      <h3>{item.name.common}</h3>
                      <p><span> Population:</span> {item.population}</p>
                      <p><span>Region:</span> {item.region}</p>
                      <p><span> Capital:</span> {item.capital}</p>
                    </div>
                  </div>
                </div>
              )
            })
          }

        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
