import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from '../components/Header'
import SearchAndDropDown from '../components/SearchAndDropDown'

const defaultEndpoint = `https://restcountries.com/v3.1/all`;

export async function getServerSideProps() {
  const res = await fetch(defaultEndpoint)
  const data = await res.json()
  return {
    props: {
      data
    }
  }
}

const regions = [
  {
    id: 1,
    value: "Africa"
  },
  {
    id: 2,
    value: "America"
  },
  {
    id: 3,
    value: "Asia"
  },
  {
    id: 4,
    value: "Europe"
  },
  {
    id: 5,
    value: "Oceania"
  },
]

export default function Home({ data }) {

  return (
    <div className={styles.container}>
      <Head>
        <title>Rest Countries</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header />

        <div className={styles.grid}>

          <SearchAndDropDown
            title="Filter by Region"
            regions={regions}
          />

          {
            data.map((item, index) => {
              return (
                <div key={index} className={styles.card}>
                  <div className={styles.image}>
                    <Image src={item.flags.svg} width="300px" height="200px" layout="responsive" objectFit="cover" alt="country flag" />
                  </div>
                  <div className={styles.cardInfo}>
                    <div className={styles.info}>
                      <h3>{item.name.common}</h3>
                      <p><span> Population:</span> {item.population}</p>
                      <p><span>Region:</span> {item.region}</p>
                      <p><span> Capital:</span> {item.capital}</p>
                    </div>
                  </div>
                </div>
              )
            })
          }

        </div>
      </main>


    </div>
  )
}
